import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

export class LoginUserDto {
  @ApiProperty({
    description: 'Token generated by firebase.',
    type: String,
    required: true,
  })
  @IsNotEmpty()
  @IsString()
  firebaseToken: string;
}
