import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

export class ValidateTokenDto {
  @ApiProperty({
    description: 'Token generated by firebase.',
    type: String,
    required: true,
  })
  @IsNotEmpty()
  @IsString()
  token: string;
}
